#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"

Bundler.require

lib_path = File.expand_path('../lib', __dir__)
$:.unshift(lib_path) if !$:.include?(lib_path)
require 'manifold/tools/cli'

Signal.trap('INT') do
  warn("\n#{caller.join("\n")}: interrupted")
  exit(1)
end

begin
  Manifold::Tools::Cli.start
rescue Manifold::Tools::Cli::Error => err
  puts "ERROR: #{err.message}"
  exit 1
end

